name: tech_task
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  json_serializable: ^3.2.3
  shared_preferences: ^0.5.4+8
  rxdart: ^0.22.6
  provider: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:


flutter:
  uses-material-design: true

